### ISSUE TITLE
野坂・ジャクリーヌ・風音の誕生日について

### ISSUE THREAD

**Issue by sota-favorite** [Assault-Lily/LuciaDB#111]
私立ルドビコ女学院3年、野坂・ジャクリーヌ・風音様のお誕生日ですが、1月26日になります。
情報ソースは、ルド女ライブショー及び真実の刃（再演）のパンフレットになります。
もし宜しければご更新頂けると幸いです。

**Comment by sota-favorite** [comment]
再度確認したら更新されてましたね…
自分の確認不足でした…すみません。

**Comment by fvh-P** [comment]
@sota-favorite 
ありがとうございます。私の方でも正しく登録されていることを確認しました。
https://github.com/Assault-Lily/LuciaDB/blob/master/RDFs/lily_ludovico.ttl#L2246

今後とも LuciaDB をよろしくお願いいたします。
こちらcloseします。
